// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using Xamarin.Forms;

namespace WizLightUniversal.macOS
{
	public partial class Container : NSViewController
	{
		private NSViewController innerViewController;

		public Container(IntPtr handle) : base(handle)
		{
		}

		public void SetContent(NSViewController contentController)
        {
			innerViewController = contentController;
		}

		public override void ViewDidLoad()
        {
			base.ViewDidLoad();
			AddChildViewController(innerViewController);
			Content.AddSubview(innerViewController.View);
			innerViewController.View.Frame = Content.Frame;
		}

		public static Container FreshController()
		{
			var storyboard = NSStoryboard.FromName("Main", null);

			Container controller = (Container)
				storyboard.InstantiateControllerWithIdentifier("Container");

			return controller;
		}
	}
}
